import type { Metadata } from "next";
import { DynaPuff, Roboto,Jua } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import NavBar from "@/components/customComponents/NavBar";
import { ThemeProvider } from "@/components/customComponents/ThemeProvider";
const fontTitle = DynaPuff({
  weight: "400",
  variable: "--font-title",
  subsets: ["latin"],
});

const fontBody = Roboto({
  weight: "400",
  variable: "--font-body",
  subsets: ["latin"],
});
const fontPara = Jua({
   weight: "400",
  variable: "--font-para",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontTitle.variable} ${fontBody.variable} ${fontPara.variable} antialiased`}
      >
        
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <NavBar />
            <div className="pb-[70px] lg:pb-0">{children}</div>
            <Toaster />
           
          </ThemeProvider>
      
      </body>
    </html>
  );
}
